theme: jekyll-theme-dinky
title: Welcome to  the Alinka213's  Homepage!
description:  Learning how to use Github to create new web-sites and to edit them. Moreover we are training to frade this site with a theme.
